/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Roberto MS (https://sketchfab.com/RobertoMS)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/strig-kabu-mole-decor-2577bdfe884d406eb2a5a8860c95e039
Title: [Strig & Kabu] Mole Decor
*/

import { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import { animated } from '@react-spring/three';

import forestScene from '../assets/3d/forest.glb';

const Forest = ({ isRotating, setIsRotating, setCurrentStage, ...props }) => {
    const forestRef = useRef();

    const { gl, viewport } = useThree();
    const { nodes, materials } = useGLTF(forestScene)
    
    const lastX = useRef(0);
    const rotatitonSpeed = useRef(0);
    const dampingFactor = 0.95;

    const handlePointerDown = (e) => {
        e.stopPropagation();
        e.preventDefault();
        setIsRotating(true);

        const clientX = e.touches 
            ? e.touches[0].clientX
            : e.clientX;

        lastX.current = clientX;
    }

    const handlePointerUp = (e) => {
        e.stopPropagation();
        e.preventDefault();
        setIsRotating(false);
    }

    const handlePointerMove = (e) => {
        e.stopPropagation();
        e.preventDefault();

        if(isRotating) {
            const clientX = e.touches 
                ? e.touches[0].clientX
                : e.clientX;

            const delta = (clientX - lastX.current) / viewport.width;
            
            forestRef.current.rotation.y += delta * 0.01 * Math.PI;
            lastX.current = clientX;
            rotatitonSpeed.current = delta * 0.01 * Math.PI;
        }
    }

    const handleKeyDown = (e) => {
        if(e.key === 'ArrowLeft') {
            if(!isRotating) setIsRotating(true);
            forestRef.current.rotation.y += 0.01 * Math.PI;
            rotatitonSpeed.current = 0.0125;
        } else if(e.key === 'ArrowRight') {
            if(!isRotating) setIsRotating(true);
            forestRef.current.rotation.y -= 0.01 * Math.PI;
            rotatitonSpeed.current = -0.0125;
        }
    }

    const handleKeyUp = (e) => {
        if(e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
            setIsRotating(false);
        }
    }
    
    useFrame(() => {
        if(!isRotating) {
            rotatitonSpeed.current *= dampingFactor;

            if(Math.abs(rotatitonSpeed.current) < 0.001) {
                rotatitonSpeed.current = 0;
            }

            forestRef.current.rotation.y += rotatitonSpeed.current;
        } else {
            const rotation = forestRef.current.rotation.y;

            const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

            // Set the current stage based on the island's orientation
            switch (true) {
                case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
                setCurrentStage(4);
                break;
                case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
                setCurrentStage(3);
                break;
                case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
                setCurrentStage(2);
                break;
                case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
                setCurrentStage(1);
                break;
                default:
                setCurrentStage(null);
            }
        }
    })

    useEffect(() => {
        const canvas = gl.domElement;
        canvas.addEventListener('pointerdown', handlePointerDown);
        canvas.addEventListener('pointerup', handlePointerUp);
        canvas.addEventListener('pointermove', handlePointerMove);
        document.addEventListener('keydown', handleKeyDown);
        document.addEventListener('keyup', handleKeyUp);

        return () => {
            canvas.removeEventListener('pointerdown', handlePointerDown);
            canvas.removeEventListener('pointerup', handlePointerUp);
            canvas.removeEventListener('pointermove', handlePointerMove);
            document.removeEventListener('keydown', handleKeyDown);
            document.removeEventListener('keyup', handleKeyUp);
        }
    }, [gl, handlePointerDown, handlePointerUp, handlePointerMove]);

    return (
        <animated.group ref={forestRef} {...props}>
            <mesh
                geometry={nodes.SM_Decoration_MiningLamp01_M_LanternGlass_0.geometry}
                material={materials.M_LanternGlass}
            />
            <mesh
                geometry={nodes.SM_Decoration_MiningLamp01_M_Lantern_0.geometry}
                material={materials.M_Lantern}
            />
            
            <mesh
                geometry={nodes.SM_Decoration_Pickaxe_M_Pickaxe_0.geometry}
                material={materials.M_Pickaxe}
            />
            <mesh
                geometry={nodes.SM_Tree_01_M_Trees_Leaves_0.geometry}
                material={materials.M_Trees_Leaves}
            />
            <mesh
                geometry={nodes.SM_Tree_01_M_Tree_Oak_01_0.geometry}
                material={materials.M_Tree_Oak_01}
            />
            <mesh
                geometry={nodes.SM_Tree_03_M_Trees_Leaves_0.geometry}
                material={materials.M_Trees_Leaves}
            />
            <mesh
                geometry={nodes.SM_Tree_03_M_Tree_Oak_01_0.geometry}
                material={materials.M_Tree_Oak_01}
            />
            <mesh
                geometry={nodes.SM_Pebbles_01_M_Pebbles_0.geometry}
                material={materials.M_Pebbles}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Grass_Short_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_02_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Forgetme_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Fern_02_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Fern_01_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Clovers_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Ivy_03_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Ivy_02_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Bluebell_01_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Ivy_04_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh 
                geometry={nodes.SM_Ivy_05_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Fern_03_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Bluebell_02_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Clovers1_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Clovers2_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Clovers3_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Clovers4_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Forgetme1_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Forgetme2_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Fern_04_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Fern_05_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_03_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_04_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_05_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_06_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_07_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_08_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_09_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh 
                geometry={nodes.SM_Plants_Grass_010_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_011_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_012_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass1_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass2_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass3_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass4_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass5_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass6_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass7_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass8_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass9_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass10_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass11_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass12_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass13_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass14_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass15_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass16_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass17_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass18_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass19_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass20_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass21_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass22_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass23_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass24_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass25_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass26_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass27_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass28_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass29_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass30_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass31_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Clovers5_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Clovers6_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Forgetme3_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Clovers7_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass32_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass33_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass34_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass35_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass36_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass37_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass38_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass39_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh 
                geometry={nodes.SM_Plant_Shortgrass40_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass41_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass42_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass43_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass44_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass45_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass46_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass47_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass48_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass49_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass50_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass51_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass52_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass53_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass54_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass55_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass56_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass57_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass58_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass59_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass60_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass61_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass62_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass63_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass64_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass65_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass66_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass67_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass68_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass69_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass70_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass71_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass72_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass73_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass74_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass75_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass76_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass77_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass78_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Shortgrass79_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Fern_06_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_013_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_014_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_015_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_016_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_017_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_018_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_019_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plants_Grass_020_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Plant_Fern_07_M_Plants_0.geometry}
                material={materials.M_Plants}
            />
            <mesh
                geometry={nodes.SM_Ground_M_Ground_0.geometry}
                material={materials.M_Ground}
            />
            <mesh
                geometry={nodes.SM_Fog_001_M_Fog_0.geometry}
                material={materials.M_Fog}
            />
            <mesh
                geometry={nodes.SM_Fog_002_M_Fog_0.geometry}
                material={materials.M_Fog}
            />
            <mesh
                geometry={nodes.SM_Fog_003_M_Fog_0.geometry}
                material={materials.M_Fog}
            />
            <mesh
                geometry={nodes.SM_Pebbles_02_M_Pebbles_0.geometry}
                material={materials.M_Pebbles}
            />
            <mesh
                geometry={nodes.SM_Pebbles_03_M_Pebbles_0.geometry}
                material={materials.M_Pebbles}
            />
            {/* <mesh
                geometry={nodes.PS_SmokeCloud_001_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            />
            <mesh
                geometry={nodes.PS_SmokeCloud_002_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            />
            <mesh
                geometry={nodes.PS_SmokeCloud_003_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            />
            <mesh
                geometry={nodes.PS_SmokeCloud_004_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            />
            <mesh
                geometry={nodes.PS_SmokeCloud_005_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            />
            <mesh
                geometry={nodes.PS_SmokeCloud_006_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            />
            <mesh
                geometry={nodes.PS_SmokeCloud_007_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            />
            <mesh
                geometry={nodes.PS_SmokeCloud_008_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            />
            <mesh
                geometry={nodes.PS_SmokeCloud_009_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            />
            <mesh
                geometry={nodes.PS_SmokeCloud_0010_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            />
            <mesh
                geometry={nodes.PS_SmokeCloud_0011_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            />
            <mesh 
                geometry={nodes.PS_SmokeCloud_0012_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            />
            <mesh
                geometry={nodes.PS_SmokeCloud_0013_M_SmokeCloud_0.geometry}
                material={materials.M_SmokeCloud}
            /> */}
            <mesh
                geometry={nodes.PS_Firefly_001_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_002_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_003_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_004_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_005_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_006_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_007_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_008_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_009_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0010_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0011_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0012_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0013_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0014_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0015_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0016_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0017_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0018_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0019_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0020_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0021_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
            <mesh
                geometry={nodes.PS_Firefly_0022_M_Firefly_0.geometry}
                material={materials.M_Firefly}
            />
        </animated.group>
    )
}

export default Forest;