/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: That_Noodle_Guy (https://sketchfab.com/Elfredy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fennec-fox-c2b49407c2864402af1f27a338efcf49
Title: Fennec Fox
*/

import { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useSpring, animated } from '@react-spring/three';

import foxScene from '../assets/3d/fox.glb';
import { useFrame } from '@react-three/fiber';

const Fox = () => {
    const foxRef = useRef();
    const { scene, animations } = useGLTF(foxScene);
    const { actions } = useAnimations(animations, foxRef);

    useEffect(() => {
        actions['Walk'].play();
    }, []);

    useFrame(({ camera }) => {
        
        // Check if the fox reached a certain endpoint relative to the camera
        if(foxRef.current.position.x > camera.position.x + 5) {
            // Change direction to forward and rotate the fox 180 degrees on the y-axis
            foxRef.current.rotation.y = Math.PI;
        } else if(foxRef.current.position.x < camera.position.x - 5) {
            // Change direction backward and reset the fox's rotation
            foxRef.current.rotation.y = 0;
        }

        // Update the X and Z positions based on the direction
        if(foxRef.current.rotation.y === 0) {
            // Moving backward
            foxRef.current.position.x += 0.003;
            foxRef.current.position.y += 0.0005;
            foxRef.current.position.z -= 0.0009;
        } else {
            // Moving forward
            foxRef.current.position.x -= 0.003;
            foxRef.current.position.y -= 0.0008;
            foxRef.current.position.z += 0.001;
        }
    })

    return (
        <mesh 
            position={[5, 0, 1]}
            rotation={[0, 3.5, -0.2]}
            scale={[0.01, 0.01, 0.01]}
            ref={foxRef}
        >
            <primitive object={scene} />
        </mesh>
        // <group ref={foxRef} {...props} >
        //     <group name="Sketchfab_Scene">
        //         <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        //         <group name="d201120cf1ec4e068716cd77a02dc4cdfbx" rotation={[Math.PI / 2, 0, 0]}>
        //             <group name="Object_2">
        //             <group name="RootNode">
        //                 <group name="Object_4">
        //                 <primitive object={nodes._rootJoint} />
        //                 <skinnedMesh
        //                     name="Object_7"
        //                     geometry={nodes.Object_7.geometry}
        //                     material={materials.CH_NPC_MOB_FennecFox_MI_LTS}
        //                     skeleton={nodes.Object_7.skeleton}
        //                 />
        //                 <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
        //                 <group
        //                     name="Cinema_4D_Editor"
        //                     position={[65.06, 56.042, 102.993]}
        //                     rotation={[Math.PI, 0.991, 2.89]}>
        //                     <group name="Object_53" />
        //                 </group>
        //                 <group name="AN_NPC_MOB_FennecFox_SK_LTS" rotation={[-Math.PI / 2, 0, 0]} />
        //                 </group>
        //             </group>
        //             </group>
        //         </group>
        //         </group>
        //     </group>
        // </group>
    )
}

export default Fox;
